language: node_js

node_js:
  - "stable"

before_script:
  - npm i
  - npm i --only=dev
after_success:
  - npm run coveralls

deploy:
  provider: heroku
  api_key:
    secure: 901bd999-6462-47eb-8b0e-d396dee67b94
  app: recipes-mongodb-api
